# Generated by Django 5.0.1 on 2025-05-30 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_remove_response_answers_remove_response_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='responses',
            field=models.ManyToManyField(blank=True, related_name='responses', to='quiz.responseanswer'),
        ),
    ]
